# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuración de variables globales
UBUNTU_VERSION = {{ cookiecutter.ubuntu_version }}
BOX_NAME = case UBUNTU_VERSION
when "20.04" then "ubuntu/focal64"
when "22.04" then "ubuntu/jammy64"
when "24.04" then "ubuntu/noble64" # Imagen aún no disponible por ubuntu (ene-2025)
else raise "Error: Versión de Ubuntu no soportada (#{UBUNTU_VERSION})"
end

Vagrant.configure("2") do |config|
  config.vm.define "{{ cookiecutter.vm_define.replace('/', '-').replace('.', '-') }}" do |machine|
    # Configuración de la máquina virtual
    machine.vm.box = BOX_NAME
    machine.vm.hostname = "{{ cookiecutter.hostname }}" # Establece el nombre del host, ejemplo "ubuntu-<nombre del desarrollador>" o "vagrant-host"
    machine.vm.boot_timeout = 360 # Esto le dará a la máquina virtual más tiempo para arrancar antes de que Vagrant considere que ha fallado
    machine.vm.box_check_update = false # Evita la actualización del box
    machine.vm.disk :disk, size: "{{ cookiecutter.disk_size}}", primary: true

    # Configuración de red
    machine.vm.network "private_network",
    type: "dhcp", # Esto permite que la IP se asigne mediante DHCP de forma automática
    virtualbox__intnet: true, # Esto es útil para configurar redes privadas dentro de tus máquinas virtuales.
    auto_config: true
    
    # permite redirigir los puertos de la VM (dispinobles solo de 1 a 65535).
    machine.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    machine.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
    machine.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
    machine.vm.network "forwarded_port", guest: 5432, host: 5432, id: "pgsql", auto_correct: true

    # Habilitar el reenvío del agente SSH
    config.ssh.forward_agent = true

    # Configuración del proveedor
    machine.vm.provider "{{ cookiecutter.provider }}" do |vb|
      vb.name = box_name.gsub('/', ' ').gsub('64', '')
      vb.memory = {{ cookiecutter.memory }}
      vb.cpus = {{ cookiecutter.processors }}
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    # Provisión de la máquina virtual
    machine.vm.provision "shell", inline: <<-SHELL
      # Actualizar paquetes
      echo "-----> Actualizando paquetes y dependencias..."
      apt-get update && apt-get upgrade -y
      apt-get install -y build-essential libssl-dev libffi-dev libpq-dev gcc \
                         apt-transport-https ca-certificates curl software-properties-common

      # Instalar Docker
      echo "-----> Instalando Docke..."
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      usermod -aG docker $USER

      # Instalar Docker Compose
      echo "-----> Instalando Docker Compose..."
      DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": \"\K.*?(?=\")')
      curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

      # Instalar PostgreSQL
      echo "-----> Instalando Postgresql..."
      sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      apt-get update
      apt-get install -y postgresql-14

      # Instalar Nginx
      echo "-----> Instalando Nginx..."
      apt-get install -y nginx

      # Instalar Node.js versión específica
      echo "-----> Instalando NodeJs..."
      NODE_VERSION={{ cookiecutter.node_version }}
      curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
      apt-get install -y nodejs

      # Instalar Git
      echo "-----> Instalando GIT..."
      apt-get install -y git

      # Verificar si Python 3.10 y los paquetes necesarios están instalados
      echo "-----> Verificando si Python 3.10 y dependencias ya están instalados..."
      if ! dpkg -l | grep -q python3.10; then
          echo "-----> Instalando Python 3.10..."
          apt-get install -y python3.10
      fi

      if ! dpkg -l | grep -q python3.10-distutils; then
          echo "-----> Instalando python3.10-distutils..."
          apt-get install -y python3.10-distutils
      fi

      if ! dpkg -l | grep -q python3.10-venv; then
          echo "-----> Instalando python3.10-venv..."
          apt-get install -y python3.10-venv
      fi

      # Instalar o actualizar pip a la última versión disponible
      echo "-----> Instalando o actualizando pip..."
      curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

    SHELL

    # Mensaje de finalización
    machine.vm.post_up_message = "{{ cookiecutter.vm_define }} provisionada correctamente"
  end
end
